"""Compatibility wrapper for legacy imports."""

from ..core.support_prompt import (
    DEFAULT_SUPPORT_PROMPT_INITIAL_THRESHOLD,
    DEFAULT_SUPPORT_PROMPT_LONG_SNOOZE,
    DEFAULT_SUPPORT_PROMPT_MEDIUM_SNOOZE,
    DEFAULT_SUPPORT_PROMPT_SHORT_SNOOZE,
    SUPPORT_PROMPT_CHOICE_CANNOT_DONATE,
    SUPPORT_PROMPT_CHOICE_NOT_SURE,
    SUPPORT_PROMPT_CHOICE_SUPPORT,
    SupportPrompt,
)

__all__ = [
    "DEFAULT_SUPPORT_PROMPT_INITIAL_THRESHOLD",
    "DEFAULT_SUPPORT_PROMPT_LONG_SNOOZE",
    "DEFAULT_SUPPORT_PROMPT_MEDIUM_SNOOZE",
    "DEFAULT_SUPPORT_PROMPT_SHORT_SNOOZE",
    "SUPPORT_PROMPT_CHOICE_CANNOT_DONATE",
    "SUPPORT_PROMPT_CHOICE_NOT_SURE",
    "SUPPORT_PROMPT_CHOICE_SUPPORT",
    "SupportPrompt",
]
